name: jala_form
description: "A form management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  permission_handler: ^12.0.1
  printing: ^5.11.1
  shared_preferences: ^2.2.2
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.1.2
  form_builder_image_picker: ^4.1.0
  uuid: ^4.3.3
  open_file: ^3.3.2
  intl: ^0.20.2
  share_plus: ^11.0.0
  excel: ^4.0.6
  http: ^1.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  logger: ^2.5.0

  
  # âœ… Use an older stable version that definitely works
  flutter_local_notifications: ^19.2.1

  
  timezone: ^0.10.1
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4


  # Animation libraries
  flutter_animate: ^4.2.0+1
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.0
  universal_html: ^2.2.4

  url_launcher: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - .env

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500